In [1]:
import numpy as np

In [2]:
tags = ['DT', 'NN', 'VB']
words = ['the', 'cat', 'sat']
initial_prob = {'DT': 1.0, 'NN': 2.0, 'VB': 3.0}
transition_prob = {
    ('DT', 'NN'): 1.0,
    ('NN', 'VB'): 2.0
}
emission_prob = {
    ('the', 'DT'): 1.0,
    ('cat', 'NN'): 2.0,
    ('sat', 'VB'): 3.0
}

n_tags = len(tags)
n_words = len(words)

viterbi = np.zeros((n_tags, n_words))
backpointer = np.zeros((n_tags, n_words), dtype=int)

for i, tag in enumerate(tags):
    viterbi[i, 0] = initial_prob.get(tag, 0) * emission_prob.get((words[0], tag), 0)
    backpointer[i, 0] = 0

for t in range(1, n_words):
    for i, current_tag in enumerate(tags):
        max_prob = 0
        max_state = 0
        for j, previous_tag in enumerate(tags):
            prob = viterbi[j, t-1] * transition_prob.get((previous_tag, current_tag), 0) * emission_prob.get((words[t], current_tag), 0)
            if prob > max_prob:
                max_prob = prob
                max_state = j
        viterbi[i, t] = max_prob
        backpointer[i, t] = max_state

final_prob = 0
final_state = 0
for i in range(n_tags):
    if viterbi[i, n_words-1] > final_prob:
        final_prob = viterbi[i, n_words-1]
        final_state = i

best_path = [final_state]
for t in range(n_words-1, 0, -1):
    final_state = backpointer[final_state, t]
    best_path.insert(0, final_state)

print("Tagged Sentence:")
for word, state in zip(words, best_path):
    print(f"{word} -> {tags[state]}")

print("\nFinal Probability:", final_prob)
print("\nViterbi Table:")
print(viterbi)

Tagged Sentence:
the -> DT
cat -> NN
sat -> VB

Final Probability: 12.0

Viterbi Table:
[[ 1.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0. 12.]]
